### ISSUE TITLE
Cmd line or configfile start of RX and TX audio

### ISSUE THREAD

**Issue by ON4BCB** [dh1tw/remoteAudio#7] opened 2017-08-08 23:06 UTC
please add the feature to start by Cmd line or config file  RX and TX audio instead of via a browser

**Comment by dh1tw** [comment] 2017-08-08 23:22
Thanks @ON4BCB, I just saw that this is actually a duplicate of #5

**Comment by dh1tw** [comment] 2019-11-15 00:59
This has been solved in v0.4.0. See #5 for the details.

**Closed by dh1tw** 2019-11-15 00:59 UTC
Labels: duplicate
